name: GitHub Pages

on:
  push:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:

      ############################################################################
      # Build the site using Hugo and ensure that it's working correctly.
      ############################################################################

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show configuration
        run: |
          echo "Hugo version: $(hugo version)"
          echo "Python version: $(python --version)"
          echo "------------------------"
          echo "Hugo configuration:"
          hugo config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r deploy_tools/requirements.txt

      - name: Download compendium entries
        run: python -m deploy_tools.scrape_zotero "${{ secrets.API_KEY }}"

      - name: Build
        run: |
          python -m deploy_tools.get_dependencies
          python -m deploy_tools.generate_compendium data/data.bib
          mkdir -p public
          hugo --minify
          cp -r deploy_tools/additional_files/* public/

      - name: Add Zotero data
        run: |
          mkdir -p public/data/
          cp data/*.bib public/data/

      - name: Log the public/ directory structure
        run: find public/ -type f

      ############################################################################
      # Run tests
      ############################################################################

      - name: Pre-commit hook check
        run: pre-commit install && pre-commit run --all-files

      ############################################################################
      # Deploy the site to GitHub pages. Only triggered by pushes to master.
      ############################################################################

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: The-Encryption-Compendium/the-encryption-compendium.github.io
          publish_branch: master
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
